### PR TITLE
Design Review

### PR DESCRIPTION
**Pull request by jj-zhang**

### CODE REVIEW

**Comment by gkwan-ibm** [comment]
hi @lauracowen (Stakeholder), @yeekangc  (Stakeholder),  @kathrynkodama (SME)

Darren is drafting this guide for Intellij. I would like to use this PR as a channel for the design review. You can review by  
- [Files  changed](https://github.com/OpenLiberty/draft-guide-intellij/pull/46/files), 
- https://github.com/OpenLiberty/draft-guide-intellij/blob/update-seo/README.adoc
- http://lgdev1.fyre.ibm.com:4020/guides/intellij.html

You only need to review the Design Review section for the title, description, SEO metadata ([by raw](https://raw.githubusercontent.com/OpenLiberty/draft-guide-intellij/update-seo/README.adoc)), and the outlines. 

We will address your feedback by this PR until we get all your approval.

**Review by lauracowen — COMMENTED** [review]
Are Proposals 1 and 2 alternatives and only one will be provided in the guide? Is there a reason why the MicroProfile Starter is Proposal 2? Assuming it works ok I'd expect that to be the easier/quicker/more productive way to work (though I've not used it yet)?

In Developing, have the "write" the application (which I guess would be to add a class that we provide for the incomplete app?) rather than "update". Avoid "update" unless that's the point of the guide (which it isn't here).

What will the app consist of for this guide? What will be in `start` vs `finish`?

In "What you'll learn", I know this is just notes for you, but it would be useful to be thinking and stating things clearly in terms of the user's perspective, of what the user learns, even at this stage (as opposed to what we want to show them). So rather than what you've got as notes for that section, more appropriate would be "Learn how to build and test a simple REST service using Intellij." (which could be the abstract for the guide actually). I'm not sure it's even necessary to make a big deal about Open Liberty Tools (at least in the intro). While it's a project in its own right to us, to them it's just a plugin that enables them to use the tools they like using. I think your SEO tags look fine as they are though.

Not sure we should be showing how to install Intellji itself (if that's what the prereqs section means) - we should just tell them that they need to install the OLT plugin through whatever the usual Intellij mechanism is - do they have a marketplace type of thing?

In Debugging, are you going to have a deliberate error in the app that is shown by the debugger?

**Comment by gkwan-ibm** [comment]
@lauracowen 
>Are Proposals 1 and 2 alternatives and only one will be provided in the guide? Is there a reason why the MicroProfile Starter is Proposal 2? Assuming it works ok I'd expect that to be the easier/quicker/more productive way to work (though I've not used it yet)?

After I tried MicroProfile Starter, I think the guide should use MicroProfile Starter to create a Liberty project. It is more reasonable than import project for developers. If decide to use this approach, the app probably won't be similar to the system or inventory  services. The MP starter generates REST project which uses service-a and service-b. Of course, we can make them behave as same as the system or inventory  services. An alternative is to wait for Liberty starter available.

>In Developing, have the "write" the application (which I guess would be to add a class that we provide for the incomplete app?) rather than "update". Avoid "update" unless that's the point of the guide (which it isn't here).

Yes, update app means create or replace files

> What will the app consist of for this guide? What will be in start vs finish?

Pending on the about decision, probably only finish directory is enough. The guide will ask users to create a project by MP starter at any location, create/replace the files, and then...

**Comment by gkwan-ibm** [comment]
Decided go for Proposal 1 and will be updated to use Liberty starter when it is available.

**Comment by yeekangc** [comment]
+1 to focus on "Importing existing project" first.  "Create new project" should come in with Liberty Starter.

What is the proposed title for the guide?

**Review by yeekangc — COMMENTED** [review]
Found the proposed title.  I missed it for some reason.  Sorry!

Please take a look at my changes.

**Comment by jj-zhang** [comment]
@lauracowen 

> Not sure we should be showing how to install Intellji itself (if that's what the prereqs section means) - we should just tell them that they need to install the OLT plugin through whatever the usual Intellij mechanism is - do they have a marketplace type of thing?

IntelliJ has a marketplace to install plugins like other IDE/editors. User can download the OLT plugin directly from IntelliJ marketplace after OLT plugin releases.

> In Debugging, are you going to have a deliberate error in the app that is shown by the debugger?

There is no deliberate error in the app. The server will stop at the breakpoint user sets and user can examine the state of the JVM. This section helps user understand how `debug` section of IntelliJ works.

**Comment by gkwan-ibm** [comment]
@meswan

**Comment by jj-zhang** [comment]
@lauracowen 
1. For the debug session, do you think it’s better to intentionally create an error and ask user to debug it? Right now there is no deliberate error in the app. The server will stop at the breakpoint user sets and user can examine the state of the JVM. This section helps user understand how debug section of IntelliJ works.
2. Is it necessary to mention installation of `open liberty tool` in the `Additional prerequisites` section?

**Comment by jj-zhang** [comment]
@meswan 
I'll close this PR. Please create a new one and continue this conversation. Thanks.

**Pull request closed without merging**
